#ifndef ETHERNETSCANNERSDKDEFINE_H
#define ETHERNETSCANNERSDKDEFINE_H

#define ETHERNETSCANNER_TCPBUFSIZE                          0xFFFF
#define ETHERNETSCANNER_TCPSCANNERDISCONNECTED              0
#define ETHERNETSCANNER_TCPSCANNERCONNECTING                1
#define ETHERNETSCANNER_TCPSCANNERDISCONNECTING             2
#define ETHERNETSCANNER_TCPSCANNERCONNECTED                 3

#define ETHERNETSCANNER_FRAMECHECKERROR                     -1
#define ETHERNETSCANNER_FRAMECHECKOK                        1

#define ETHERNETSCANNER_PEAKSPERCMOSSCANLINEMAX	            4
#define ETHERNETSCANNER_SCANXMAX                            2048
#define ETHERNETSCANNER_BUFFERSIZEMAX                       2050 * 2050

#define ETHERNETSCANNER_GETINFOSIZEMAX                      128 * 1024
#define ETHERNETSCANNER_GETINFOINVALIDXML					-4
#define ETHERNETSCANNER_GETINFONOVALIDINFO                  -3
#define ETHERNETSCANNER_GETINFOSMALLBUFFER                  -2
#define ETHERNETSCANNER_ERROR                               -1

#define ETHERNETSCANNER_GETXZINONEWSCAN                     -1
#define ETHERNETSCANNER_GETXZIINVALIDLINDATA				-2
#define ETHERNETSCANNER_GETXZIINVALIDBUFFER					-3

#define ETHERNETSCANNER_READDATAOK                          1
#define ETHERNETSCANNER_READDATASMALLBUFFER                 -1
#define	ETHERNETSCANNER_READDATANOTSUPPORTEDMODE            -2
#define ETHERNETSCANNER_READDATAFEATURENOTDEFINED           -3

#define ETHERNETSCANNER_OK                                  0

#endif //ETHERNETSCANNERSDKDEFINE_H
